name: Metrics
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  # 英文版任务
  github-metrics-en:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: WeiErLiTeo
          filename: github-metrics-en.svg
          locale: en
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes

  # 中文版任务
  github-metrics-zh:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: WeiErLiTeo
          filename: github-metrics-zh.svg
          locale: zh_CN
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes

  # 日语版任务
  github-metrics-ja:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: WeiErLiTeo
          filename: github-metrics-ja.svg
          locale: ja
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes
