name: Metrics
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # 生成英文版图片 (文件名: github-metrics-en.svg)
      - name: English Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: WeiErLiTeo
          filename: github-metrics-en.svg
          locale: en
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes

      # 生成中文版图片 (文件名: github-metrics-zh.svg)
      - name: Chinese Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: WeiErLiTeo
          filename: github-metrics-zh.svg
          locale: zh_CN
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes

      # 生成日语版图片 (文件名: github-metrics-ja.svg)
      - name: Japanese Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: WeiErLiTeo
          filename: github-metrics-ja.svg
          locale: ja
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes
